services:
  vite-app:
    build:
      context: ./client # Assumes Dockerfile is in the same directory as docker-compose.yml
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map host port 8080 to container port 80
    volumes:
      # Mount the local Nginx configuration into the container
      - ./nginx-local.conf:/etc/nginx/conf.d/default.conf:ro
      # Optional: For faster local development, you can mount your local 'dist'
      # directory directly, bypassing the COPY in the Dockerfile for local changes.
      # This is useful if you're rebuilding the frontend often and don't want
      # to rebuild the Docker image each time.
      # However, for testing the actual built image, this line should be commented out.
      # - ./dist:/usr/share/nginx/html:ro
    environment:
      # Add any environment variables Nginx might need or your app expects
      NGINX_HOST: localhost
      NGINX_PORT: 80
    restart: unless-stopped
  server:
    build:
      context: ./server # Assumes Dockerfile is in the same directory as docker-compose.yml
      dockerfile: Dockerfile
    ports:
      - "3333:3001" # Map host port 8080 to container port 80
    env_file:
      - server/.env
